// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACqz6fp32a65GVc-H6_6D68xgN6n0Z_8E',
    appId: '1:574284339608:web:480732f418646d2bd6b3ed',
    messagingSenderId: '574284339608',
    projectId: 'urbanwear-f0b82',
    authDomain: 'urbanwear-f0b82.firebaseapp.com',
    storageBucket: 'urbanwear-f0b82.appspot.com',
    measurementId: 'G-G2DYSHXDHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNcaQPRV0u_YvhY8Lq4ABbF5ov_sQFXM',
    appId: '1:574284339608:android:9fdef6a08c74266dd6b3ed',
    messagingSenderId: '574284339608',
    projectId: 'urbanwear-f0b82',
    storageBucket: 'urbanwear-f0b82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yf_IDNrZ1PSouBKGC6T0aDtYgHl6ksw',
    appId: '1:574284339608:ios:2eb218d878c9a000d6b3ed',
    messagingSenderId: '574284339608',
    projectId: 'urbanwear-f0b82',
    storageBucket: 'urbanwear-f0b82.appspot.com',
    iosBundleId: 'com.example.urbanwear',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8yf_IDNrZ1PSouBKGC6T0aDtYgHl6ksw',
    appId: '1:574284339608:ios:2eb218d878c9a000d6b3ed',
    messagingSenderId: '574284339608',
    projectId: 'urbanwear-f0b82',
    storageBucket: 'urbanwear-f0b82.appspot.com',
    iosBundleId: 'com.example.urbanwear',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACqz6fp32a65GVc-H6_6D68xgN6n0Z_8E',
    appId: '1:574284339608:web:3f8d5a40fe9e214cd6b3ed',
    messagingSenderId: '574284339608',
    projectId: 'urbanwear-f0b82',
    authDomain: 'urbanwear-f0b82.firebaseapp.com',
    storageBucket: 'urbanwear-f0b82.appspot.com',
    measurementId: 'G-EEKLW3LM3Y',
  );
}
